spring.application.name=historial-petpals
server.port=8089
ms.cuidadores.url=http://localhost:8085
ms.dueno.url=http://localhost:8081
ms.reserva.url=http://localhost:8086
ms.mascota.url=http://localhost:8084
ms.servicio.url=http://localhost:8082

# ?? CONEXIÓN MYSQL ??????????????????????????????????
# Crea la BD vacía en phpMyAdmin antes de arrancar.
# Hibernate generará las tablas desde las entidades.
spring.datasource.url=jdbc:mysql://localhost:3306/bd_petpals
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
