spring.application.name=MicroservicioCalendario
# CONFIGURACIÓN DEL SERVIDOR
server.port=8091

# CONFIGURACIÓN DE LA BASE DE DATOS (MySQL)
# Reemplaza 'bd_petpals_calendario' por el nombre que le des a esta nueva base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/bd_petpals
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN DE HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar colores bonitos en la consola
spring.output.ansi.enabled=always