    spring.application.name=servicios-mascotas

server.port = 8082

# ?? CONEXIÓN MYSQL ??????????????????????????????????
# Crea la BD vacía en phpMyAdmin antes de arrancar.
# Hibernate generará las tablas desde las entidades.
spring.datasource.url=jdbc:mysql://localhost:3306/bd_petpals
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
