spring.application.name=MicroServicioResenas
server.port = 8093

# ── CONEXIÓN MYSQL ──────────────────────────────────
# Crea la BD vacía en phpMyAdmin antes de arrancar.
# Hibernate generará las tablas desde las entidades.
spring.datasource.url=jdbc:mysql://localhost:3306/bd_petpals
spring.datasource.username=root
spring.datasource.password=

# ── DDL AUTO ────────────────────────────────────────
# update: crea las tablas si no existen, las actualiza
# si el modelo cambió. Ideal para desarrollo en clase.
spring.jpa.hibernate.ddl-auto=create

# ── MOSTRAR SQL ─────────────────────────────────────
# Muestra en consola el SQL que ejecuta Hibernate.
# Útil para entender qué ocurre internamente.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

//Agregare aqui los portales de los microservicios para comnectarlos
dueno-service.url=http://localhost:8081/api/duenos
cuidador-service.url=http://localhost:8085/api/cuidadores